version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6

    working_directory: ~/ebedke

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-poetry-cache-{{ checksum "poetry.lock" }}
      - run:
          name: Install dependencies with poetry
          command: |
            poetry config settings.virtualenvs.in-project true
            poetry install
      - save_cache:
          paths:
            - ~/ebedke/.venv
          key: v1-poetry-cache-{{ checksum "poetry.lock" }}
      - run:
          name: Rename example config
          command: |
            cp ~/ebedke/ebedke/config.py.example ~/ebedke/ebedke/config.py
      - run:
          name: Run pytest
          command: |
            poetry run pytest
