version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6

    working_directory: ~/ebedke

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-poetry-cache-{{ checksum "poetry.lock" }}
      - run:
          name: Install dependencies with poetry
          command: |
            poetry config settings.virtualenvs.in-project true
            poetry install
      - save_cache:
          paths:
            - ~/ebedke/.venv
          key: v1-poetry-cache-{{ checksum "poetry.lock" }}
      - run:
          name: Run linter
          command: |
            poetry run pylint --rcfile=pylintrc ebedke
      - run:
          name: Run mypy type-cheker
          command: |
            poetry run mypy --ignore-missing-imports --warn-redundant-casts --warn-unused-ignores -p ebedke
            # untyped defs are skipped by default, this will threw false positives
            # poetry run mypy --ignore-missing-imports --check-untyped-defs -p ebedke
      - run:
          name: Run pytest
          command: |
            poetry run pytest
